### ISSUE TITLE
ERROR TypeError: this.adapter_.computeBoundingRect is not a function (Angular SSR)

### ISSUE THREAD

**Issue by JeetChaudhari** [trimox/angular-mdc-web#1443]
Angular SSR build shows the following error.

ERROR TypeError: this.adapter_.computeBoundingRect is not a function
    at b.value (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-drawer.umd.js:186:159)
    at a.set [as open] (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular-mdc\web\bundles\web-drawer.umd.js:342:81)
    at updateProp (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:9475:41)
    at checkAndUpdateDirectiveInline (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:9226:23)
    at checkAndUpdateNodeInline (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10533:24)
    at checkAndUpdateNode (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10495:20)
    at prodCheckAndUpdateNode (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:11035:9)
    at Object.updateDirectives (D:\Dev\jeet-chaudhari\universal-starter\dist\server\main.js:2514:1231)
    at Object.updateDirectives (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10824:76)
    at checkAndUpdateView (D:\Dev\jeet-chaudhari\universal-starter\node_modules\@angular\core\bundles\core.umd.js:10477:18)

**Comment by trimox** [comment]
Thanks for reporting this issue.

Can you retry after upgrading to v0.40.2, as the MDC team removed the `computeBoundingRect` adapter method.

**Comment by JeetChaudhari** [comment]
@trimox You are right, this seems to be fixed, I was sure I was testing on latest repo, don't know why it came out that time. Anyways closing issue.
